#+TITLE: PPPL NSTX-U Hire Job Posting RSE II

* Position Summary
What if you could have an impact on the search for an abundant, safe, affordable and environmentally sound means of generating electricity? This is the goal of fusion energy research at the [[https://www.pppl.gov/][Princeton Plasma Physics Laboratory]] (PPPL)  a United States Department of Energy national laboratory for plasma physics and nuclear fusion science. The pace of the research toward that goal has been quickly accelerating in recent years. If that idea appeals to you, Princeton University's Research Computing department is recruiting a Research Software Engineer to join the fast-growing Research Software Engineering (RSE) Group.

In the RSE Group, we collectively provide computational research expertise to multiple divisions within the University. As a central team of software experts, we are focused on improving the quality, performance, and sustainability of Princeton's computational research software. Our group is committed to building collaborative and inclusive environments in which the best software engineering practices are valued, and to sharing and applying cross-disciplinary computational techniques in new and emerging areas.

In this position you will be an integral part of the [[https://sites.google.com/a/pppl.gov/nstx-u/home?authuser=0][NSTX-U]] group at PPPL. Each run on the NSTX-U experiment consists of a [[https://www.youtube.com/watch?v=N4yWhA1mVxA&t=444s][plasma blast or shot]]. The experiment is currently out of service for upgrade, and in preparation for its restart the team is developing a web tool that will track the full lifecycle of the shots: from the initial scientific proposal, the logging of the experimental conditions and to the presentation of the data analysis of large amount of data generated by the plasma shots. Your first responsibility in this position will be to develop this web tool.Some components of this software have already been developed and can be reused with some upgrade, other components will need to be written from scratch. This web tool will be critical to the NSTX-U experiment and will need to be fully operational when the experiment will return to operation in 2025. It will be used by everyone involved with the experiment: researchers at PPPL, Princeton University, national and international institutions, as well as technical staff. 

If you have a strong background in Software Development including web based tools developement you will have a unique opportunity to have a significant and long lasting impact on an important and exiting research.

You'll have the opportunity to regularly work closely with colleagues, faculty, student/postdoctoral researchers, and technical staff associated with Princeton University, PPPL as well as the Office of Information Technology (OIT) to enable and accelerate research software development.

* Responsibilities
- Working independently or as a self-directed team member, apply research software engineering experience to develop robust software solutions to challenging, and rapidly evolving research problems.
- Establish a set of applicable best practices (e.g., version control, continuous integration/continuous delivery, software design, programming model, etc.), and a documentation level appropriate for each project to enable long-term maintainability and sustainability of the software.
- Transfer knowledge, expertise, and methodologies by providing technical assistance and mentorship to researchers and techincal staff.
- Provide support for the users of the web tool.
- Communicate software engineering concepts to domain experts with varying degrees of software engineering knowledge.
- Independently or in collaboration with a team, develop scope and project management plans, communicate those plans with the research team and meet milestone delivery timelines. This position requires careful planning to meet the hard deadline of 2025.
- Through independent research (reading publications, etc.) and/or studying existing code bases, develop an understanding of nuclear fusion [fn:6] sufficient to converse with world-class researchers. Initiate and/or maintain open collaboration with researchers. Regularly meet with, listen to, and ask questions of researchers to ensure that engineered solutions fit the research needs. Understand and address software engineering questions that arise in research planning.
- Apply appropriate domain-specific algorithms and programming techniques to advance software engineering in nuclear physics.
- Maintain and expand knowledge of current and future software development tools and techniques, programming languages, and computing hardware.

* Essential Qualifications
- A minimum of 4 years as a Research Software Engineer or equivalent experience (e.g., graduate school, industry experience, open-source software development, etc.)
- Strong programming skills, particularly in languages used in web tool applications (e.g., Python).
- Demonstrated success in:
  – Consistently using conventional and readable coding style. 
  – Creating comprehensive and well-written documentation. 
  – Developing and maintaining reproducible build systems.
  – Using version control systems.
- Ability to learn new concepts and technologies beyond the area of core knowledge.
- Ability to communicate effectively with a diverse user base with varied technical proficiencies.
- Experience with the Linux command line.
- Demonstrated successes working in a collaborative software development environment (often geographically distributed) as well as independently.
- Ability to manage large, complex software projects involving a large and diverse user base.
- Experience working with relational database.

* Preferred Qualifications
- Background in or understanding of nuclear physics concepts.
- Experience working in a research environment.
- A Master's/Ph.D. in computer science, applied science, or another related field with a strong computational focus or equivalent experience in a research setting is preferred.
- Experience with DevOps.
- Experience with containers.

* Education
- A Bachelor's degree in computer science, engineering, sciences, or a related computational field is required.


