* Position Summary
Do you want to help solve the world's
[[https://vimeo.com/568645775][water resources]] problems? Do you have a
background in research and love to write code? Are you looking to apply
your scientific programming expertise to a novel set of research
problems? If so, Princeton University's Research Computing department is
recruiting a Research Software Engineer to join the fast-growing
Research Software Engineering (RSE) Group.

In the RSE Group, we collectively provide computational research
expertise to multiple divisions within the University. As a central team
of software experts, we are focused on improving the quality,
performance, and sustainability of Princeton's computational research
software. Our group is committed to building collaborative and inclusive
environments in which the best software engineering practices are
valued, and to sharing and applying cross-disciplinary computational
techniques in new and emerging areas.

In this position, you will be an integral part of the
[[http://maxwell.princeton.edu/#home][Maxwell lab]] housed in the Civil
and Environmental Engineering department (CEE) and the High Meadows
Environmental Institute (HMEI). Part of this group's work is to develop
novel numerical approaches to solving water resource problems. You'll
have the opportunity to work as part of a team with other RSEs; faculty,
student, postdoctoral researchers, and technical staff associated with
CEE, HMEI, the Office of Information Technology (OIT); as well as
collaborators from other institutions to enable and accelerate research
software development

If you have a strong background in scientific programming, academic
research, and an interest in hydrology, you have the right skill set to
immediately impact multiple high-profile research projects. This role
functions within a dynamic, supportive team environment that permits
diverse backgrounds to thrive, including those wanting to make a career
change and those with non-traditional career tracks, educational paths,
or life experiences. If this environment sounds like a strong match or
even an exciting challenge, we encourage you to apply and use your cover
letter to explain why you would be a good fit for the role.

* Responsibilities
** RSE (65%)
- Working independently or as a self-directed team member, apply
  research software engineering experience to develop robust software
  solutions to challenging, and rapidly evolving research problems.
- Establish a set of applicable best practices (e.g., version control,
  continuous integration/continuous delivery, software design,
  programming model, etc.), and a documentation level appropriate for
  each project to enable long-term maintainability and sustainability of
  the software.
- Port, debug, tune and potentially parallelize existing research code
  to meet criteria set by the research needs.
- Transfer knowledge, expertise, and methodologies by providing
  technical assistance and mentorship to graduate students and
  postdoctoral researchers.
- Support the user communities of the software tools developed in the
  lab (e.g. [[https://parflow.org/][ParFlow]],  [[https://vimeo.com/568645775][HydroGEN]], [[https://hydroframe.org/][HydroFrame]], [[https://sandtank.hydroframe.org/][sandtank]], and [[https://sandtank-ml.hydroframe.org/#/][sandtank-ml]]) and organize
  collaborations between those communities to bridge gaps and decrease
  redundancy.
- Communicate software engineering concepts to domain experts with
  varying degrees of software engineering knowledge.
- Independently or in collaboration with a team, develop scope and
  project management plans, communicate those plans with the research
  team and meet milestone delivery timelines.
- Work with members of the Research Computing team to develop and
  maintain research workflows on HPC clusters and help researchers use
  these workflows.

** Application of Domain Expertise (20%)
- Through independent research (reading publications, etc.) and/or
  studying existing code bases, develop an understanding of hydrology
  sufficient to converse with world-class researchers. Initiate and/or
  maintain open collaboration with researchers. Regularly meet with,
  listen to, and ask questions of researchers to ensure that engineered
  solutions fit the research needs. Understand and address software
  engineering questions that arise in research planning.

- Apply appropriate domain-specific algorithms and programming
  techniques to advance software engineering in hydrology.

** Professional Development (15%)
- Maintain and expand knowledge of current and future software
  development tools and techniques, programming languages, and computing
  hardware.

* Qualifications
** Essential Qualifications
- A minimum of 4 years as a Research Software Engineer or equivalent
  experience (e.g., graduate school, industry experience, open-source
  software development, etc.)
- Strong programming skills, particularly in languages used in our
  hydrology applications (e.g., Python and C++).
- Demonstrated success in:
  - Consistently using conventional and readable coding style.
  - Creating comprehensive and well-written documentation.
  - Developing and maintaining reproducible build systems.
  - Using version control systems.
- Ability to learn new concepts and technologies beyond the area of core
  knowledge.
- Ability to communicate effectively with a diverse user base with
  varied technical proficiencies.
- Experience with Linux, the command line, and HPC clusters environment
  (e.g., workflow manager, parallel file system).
- Demonstrated successes working in a collaborative software development
  environment ("team science", often geographically distributed) as well
  as independently.
- Education: A Bachelor's degree in computer science, engineering,
  sciences, or a related computational field is required.

** Preferred Qualifications
- Experience with parallel programming architectures, both distributed
  and threaded/shared memory.
- Background in or understanding of hydrology concepts.
- Experience working in an academic research environment.
- A Master's/Ph.D. in computer science, applied science, or another
  related field with a strong computational focus or equivalent
  experience in a research setting is preferred.
